import { describe, it, expect, vi } from "vitest";

// Stub the tools barrel so the module loads in node; getAll is injected in tests,
// and deleteAnnotation calls the (mocked) real removeAnnotation.
const { removeAnnotation } = vi.hoisted(() => ({
  removeAnnotation: vi.fn(),
}));
vi.mock("@cornerstonejs/tools", () => ({
  annotation: { state: { getAllAnnotations: vi.fn(() => []), removeAnnotation } },
  Enums: { Events: { ANNOTATION_RENDERED: "ar" } },
}));
vi.mock("@cornerstonejs/core", () => ({
  eventTarget: { addEventListener: vi.fn(), removeEventListener: vi.fn() },
  Enums: { Events: { IMAGE_RENDERED: "ir", STACK_NEW_IMAGE: "sni" } },
}));

import {
  getAnnotationDeleteTargets,
  deleteAnnotation,
  subscribeOverlayReposition,
  type OverlayAnnotation,
} from "../src/cornerstone/annotation-overlay";
import { eventTarget } from "@cornerstonejs/core";

const vp = {
  getCurrentImageId: () => "img-1",
  // identity-ish projection: x,y from world, ignore z
  worldToCanvas: ([x, y]: [number, number, number]) => [x * 10, y * 10] as [number, number],
};

const ann = (over: Partial<OverlayAnnotation> = {}): OverlayAnnotation => ({
  annotationUID: "a1",
  metadata: { toolName: "Length", referencedImageId: "img-1" },
  data: { handles: { points: [[1, 2, 0]], textBox: { worldPosition: [3, 4, 0] } } },
  ...over,
});

describe("getAnnotationDeleteTargets", () => {
  it("returns one target per tracked, on-slice annotation anchored at the label box", () => {
    const out = getAnnotationDeleteTargets(vp, () => [ann()]);
    expect(out).toEqual([{ uid: "a1", toolName: "Length", canvas: { x: 30, y: 40 } }]);
  });

  it("falls back to points[0] when there is no textBox", () => {
    const a = ann({ data: { handles: { points: [[1, 2, 0]] } } });
    const out = getAnnotationDeleteTargets(vp, () => [a]);
    expect(out[0].canvas).toEqual({ x: 10, y: 20 });
  });

  it("skips an annotation with no annotationUID (no phantom delete button)", () => {
    const noUid = ann({ annotationUID: undefined });
    const out = getAnnotationDeleteTargets(vp, () => [noUid]);
    expect(out).toEqual([]);
  });

  it("anchors a plain CircleROI on its rim, not on the unused text-box placeholder", () => {
    // Every Cornerstone annotation is born with textBox.worldPosition [0,0,0],
    // and only renderLinkedTextBoxAnnotation replaces it. CircleROI runs with
    // calculateStats:false, so that never happens and the placeholder survives —
    // anchoring there would put the "x" at the patient-coordinate origin, far
    // outside the image, and the control would be invisible.
    const circle = ann({
      annotationUID: "c1",
      metadata: { toolName: "CircleROI", referencedImageId: "img-1" },
      data: {
        handles: {
          points: [
            [1, 2, 0], // centre
            [5, 2, 0], // the rim point the user dragged to
          ],
          textBox: { worldPosition: [0, 0, 0] },
        },
      },
    });
    const out = getAnnotationDeleteTargets(vp, () => [circle]);
    expect(out).toEqual([{ uid: "c1", toolName: "CircleROI", canvas: { x: 50, y: 20 } }]);
  });

  it("still anchors measurements on their text box, which the renderer does position", () => {
    const length = ann({
      annotationUID: "m1",
      data: {
        handles: { points: [[1, 2, 0]], textBox: { worldPosition: [3, 4, 0] } },
      },
    });
    expect(getAnnotationDeleteTargets(vp, () => [length])[0].canvas).toEqual({ x: 30, y: 40 });
  });

  it("skips auto-generated, unknown tools, and annotations on other slices", () => {
    const auto = ann({ annotationUID: "x", autoGenerated: true });
    const unknown = ann({
      annotationUID: "y",
      metadata: { toolName: "Crosshairs", referencedImageId: "img-1" },
    });
    const offSlice = ann({
      annotationUID: "z",
      metadata: { toolName: "Length", referencedImageId: "img-2" },
    });
    const out = getAnnotationDeleteTargets(vp, () => [auto, unknown, offSlice]);
    expect(out).toEqual([]);
  });
});

describe("deleteAnnotation", () => {
  it("removes by uid and ignores an empty uid", () => {
    deleteAnnotation("a1");
    expect(removeAnnotation).toHaveBeenCalledWith("a1");
    removeAnnotation.mockClear();
    deleteAnnotation("");
    expect(removeAnnotation).not.toHaveBeenCalled();
  });
});

describe("subscribeOverlayReposition", () => {
  it("wires element + global listeners, filters by viewport id, and tears down", () => {
    const add = vi.fn();
    const remove = vi.fn();
    const el = { addEventListener: add, removeEventListener: remove } as unknown as HTMLElement;
    const cb = vi.fn();
    const teardown = subscribeOverlayReposition(el, () => "stack-0", cb);

    // two element listeners (IMAGE_RENDERED, STACK_NEW_IMAGE) + one global (ANNOTATION_RENDERED)
    expect(add.mock.calls.map((c) => c[0])).toEqual(["ir", "sni"]);
    const annCall = vi.mocked(eventTarget.addEventListener).mock.calls.find((c) => c[0] === "ar");
    const annHandler = annCall?.[1] as (e: unknown) => void;

    annHandler({ detail: { viewportId: "stack-9" } }); // different viewport -> ignored
    expect(cb).not.toHaveBeenCalled();
    annHandler({ detail: { viewportId: "stack-0" } }); // our viewport -> fires
    annHandler({ detail: {} }); // no id -> fires
    expect(cb).toHaveBeenCalledTimes(2);

    teardown();
    expect(remove).toHaveBeenCalledTimes(2);
    expect(vi.mocked(eventTarget.removeEventListener)).toHaveBeenCalledTimes(1);
  });
});
