import type { Types as CsToolsTypes } from "@cornerstonejs/tools";
import type { Measurement } from "../cornerstone/measurements";

type Point3 = [number, number, number];

/**
 * Build a render-ready Cornerstone annotation from a Measurement (the inverse of
 * `collectMeasurements`). Pass the returned object as the first arg to
 * `annotation.state.addAnnotation(ann, m.frameOfReferenceUID)`.
 *
 * Requirements verified against Cornerstone tools 5.0.13:
 * - `isVisible: true` is REQUIRED — the StackViewport display filter drops
 *   annotations whose `isVisible` is falsy.
 * - `metadata.referencedImageId` must equal the slice's imageId for on-slice render.
 * - `cachedStats: {}` is intentional — every tool recomputes stats from world
 *   points at render time when the target key is missing.
 * - `metadata.orbidicomResultId` is custom provenance; the manager stores the
 *   object by reference, so it survives `getAllAnnotations()` and lets the panel
 *   find/toggle/remove this annotation later.
 */
export function measurementToAnnotation(m: Measurement, resultId: string): CsToolsTypes.Annotation {
  const points: Point3[] = m.points.map((p) => [p[0], p[1], p[2]] as Point3);
  return {
    annotationUID: m.annotationUID || undefined,
    highlighted: false,
    isLocked: false,
    isVisible: true,
    invalidated: true,
    isSelected: false,
    autoGenerated: false,
    metadata: {
      toolName: m.tool,
      FrameOfReferenceUID: m.frameOfReferenceUID,
      referencedImageId: m.imageId,
      orbidicomResultId: resultId,
    } as CsToolsTypes.AnnotationMetadata,
    data: {
      label: m.label ?? "",
      handles: { points, activeHandleIndex: null },
      cachedStats: {},
      ...(m.tool === "EllipticalROI" ? { initialRotation: 0 } : {}),
    },
  };
}
